MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Models/ErrorViewModel.cs
using System;

namespace MvcExamenPracticoAzureMariaDelMarCarrionGarcia.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Models/Personaje.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcExamenPracticoAzureMariaDelMarCarrionGarcia.Models
{
    public class Personaje
    {
        public int IdPersonaje { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public int IdSerie { get; set; }
    }
}

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Models/Serie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcExamenPracticoAzureMariaDelMarCarrionGarcia.Models
{
    public class Serie
    {
        public int IdSerie { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public double Puntuacion { get; set; }
        public int Anio { get; set; }
    }
}

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcExamenPracticoAzureMariaDelMarCarrionGarcia.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcExamenPracticoAzureMariaDelMarCarrionGarcia.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Controllers/SeriesClientController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcExamenPracticoAzureMariaDelMarCarrionGarcia.Controllers
{
    public class SeriesClientController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Series()
        {
            return View();
        }

        public IActionResult PersonajesSerie()
        {
            return View();
        }

        public IActionResult InsertarSerie()
        {
            return View();
        }

        public IActionResult EliminarSerie()
        {
            return View();
        }
    }
}

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Controllers/SeriesServidorController.cs
using Microsoft.AspNetCore.Mvc;
using MvcExamenPracticoAzureMariaDelMarCarrionGarcia.Models;
using MvcExamenPracticoAzureMariaDelMarCarrionGarcia.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcExamenPracticoAzureMariaDelMarCarrionGarcia.Controllers
{
    public class SeriesServidorController : Controller
    {
        private SeriesService service;

        public SeriesServidorController(SeriesService service)
        {
            this.service = service;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Series()
        {
            List<Serie> series = await this.service.GetSeriesAsync();
            return View(series);
        }

        public async Task<IActionResult> DetallesSerie(int idSerie)
        {
            Serie serie = await this.service.FindSerieAsync(idSerie);
            return View(serie);
        }

        public IActionResult PersonajesSerie()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PersonajesSerie(int idSerie)
        {
            List<Personaje> series = await this.service.PersonajesSerieAsync(idSerie);
            return View(series);
        }

        public IActionResult CreatePersonaje()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePersonaje(string nombre, string imagen, int idSerie)
        {
            await this.service.InsertarPersonajeAsync(nombre, imagen, idSerie);
            ViewBag.Mensaje = "Personaje creado.";
            return View();
        }

        public IActionResult UpdateSerie()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateSerie(int idSerie, string nombre, string imagen, double puntuacion, int anio)
        {
            await this.service.ModificarSerieAsync(idSerie, nombre, imagen, puntuacion, anio);
            ViewBag.Mensaje = "Serie modificada.";
            return View();
        }

        public IActionResult DeletePersonaje()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DeletePersonaje(int idPersonaje)
        {
            await this.service.EliminarPersonajeAsync(idPersonaje);
            ViewBag.Mensaje = "Personaje eliminado.";
            return View();
        }

        public async Task<IActionResult> MoverPersonajeSerie()
        {
            List<Serie> series = await this.service.GetSeriesAsync();
            List<Personaje> personajes = await this.service.GetPersonajesAsync();
            ViewBag.Personajes = personajes;
            return View(series);
        }

        [HttpPost]
        public async Task<IActionResult> MoverPersonajeSerie(int idPersonaje, int idSerie)
        {
            await this.service.MoverPersonajeSerieAsync(idPersonaje, idSerie);
            ViewBag.Mensaje = "Personaje movido.";
            List<Serie> series = await this.service.GetSeriesAsync();
            List<Personaje> personajes = await this.service.GetPersonajesAsync();
            ViewBag.Personajes = personajes;
            return View(series);
        }

    }
}

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Views/SeriesClient/EliminarSerie.cshtml
@section Scripts{
    <script>
        $(document).ready(function () {
            $("#botonEliminar").click(function () {
                var idSerie = $("#idSerie").val();
                var url = "https://examenpracticoazuremariadelmarcarriongarcia2022.azurewebsites.net/api/Series/" + idSerie;
                $.ajax({
                    url: url,
                    method: "DELETE",
                    success: function () {
                        $("#mensaje").html("Serie eliminada.");
                    }
                });
            });
        });
    </script>
}

<h1>Eliminar serie</h1>

<hr />

<h2 id="mensaje" style="color:darkgreen"></h2>

<h1>ID serie:</h1>
<input type="number" id="idSerie" class="form-control" />
<button type="submit" id="botonEliminar" class="btn btn-danger">Eliminar</button>

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Views/SeriesClient/Index.cshtml
<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="SeriesClient" asp-action="Series">Series</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="SeriesClient" asp-action="InsertarSerie">Crear serie</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="SeriesClient" asp-action="EliminarSerie">Eliminar serie</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="SeriesClient" asp-action="PersonajesSerie">Personajes de una serie</a>
    </li>
</ul>

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Views/SeriesClient/InsertarSerie.cshtml
@model MvcExamenPracticoAzureMariaDelMarCarrionGarcia.Models.Serie

@{
    ViewData["Title"] = "InsertarSerie";
}


@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {
            $("#botonCrear").click(function () {
                var serie = new Object();
                serie.idSerie = 0;
                serie.nombre = $("#nombre").val();
                serie.imagen = $("#imagen").val();
                serie.puntuacion = $("#puntuacion").val();
                serie.anio = $("#anio").val();
                var json = JSON.stringify(serie);
                var url = "https://examenpracticoazuremariadelmarcarriongarcia2022.azurewebsites.net/api/Series";
                $.ajax({
                    url: url,
                    method: "POST",
                    contentType: "application/json",
                    data: json,
                    success: function (data) {
                        $("#mensaje").html("Serie insertada.");
                    }
                });
            });
        });
    </script>
}






<h1>InsertarSerie</h1>

<hr />

<h2 id="mensaje" style="color:darkgreen"></h2>

<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <label asp-for="Nombre" class="control-label"></label>
            <input id="nombre" asp-for="Nombre" class="form-control" />
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Imagen" class="control-label"></label>
            <input id="imagen" asp-for="Imagen" class="form-control" />
            <span asp-validation-for="Imagen" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Puntuacion" class="control-label"></label>
            <input id="puntuacion" asp-for="Puntuacion" class="form-control" />
            <span asp-validation-for="Puntuacion" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Anio" class="control-label"></label>
            <input id="anio" asp-for="Anio" class="form-control" />
            <span asp-validation-for="Anio" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" id="botonCrear" value="Create" class="btn btn-primary" />
        </div>
    </div>
</div>

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Views/SeriesClient/PersonajesSerie.cshtml
@section Scripts{
    <script>
        $(document).ready(function () {
            $("#boton").click(function () {
                var idSerie = $("#idSerie").val();
                var url = "https://examenpracticoazuremariadelmarcarriongarcia2022.azurewebsites.net/api/Series/PersonajesSerie/" + idSerie;
                $.ajax({
                    url: url,
                    method: "GET",
                    dataType: "json",
                    success: function (data) {
                        var html = "";
                        $.each(data, function (index, serie) {
                            html += "<tr>"
                            html += "<td>" + serie.idPersonaje + "</td>";
                            html += "<td>" + serie.nombre + "</td>";
                            html += "<td> <img src='" + serie.imagen + "' style='width:300px' /> </td>";
                            html += "<td>" + serie.idSerie + "</td>";
                            html += "</tr>";
                        });
                        $("#tablaPersonajes tbody").html(html);
                    }
                });
            });
        });
    </script>
}

<h1>Personajes de una serie</h1>

<hr />

<div class="form-group">
    <label>ID serie:</label>
    <input type="number" id="idSerie" class="form-control" />
    <button type="submit" id="boton" class="btn btn-warning">Mostrar personajes</button>
</div>

<hr />

<table id="tablaPersonajes" class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Imagen</th>
            <th>ID serie</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Views/SeriesClient/Series.cshtml
@section Scripts{ 
    <script>
        $(document).ready(function () {
            var url = "https://examenpracticoazuremariadelmarcarriongarcia2022.azurewebsites.net/api/Series";
            $.ajax({
                url: url,
                method: "GET",
                dataType: "json",
                success: function (data) {
                    var html = "";
                    $.each(data, function (index, serie) {
                        html += "<tr>"
                        html += "<td>" + serie.idSerie + "</td>";
                        html += "<td>" + serie.nombre + "</td>";
                        html += "<td> <img src='" + serie.imagen + "' style='width:300px' /> </td>";
                        html += "<td>" + serie.puntuacion + "</td>";
                        html += "<td>" + serie.anio + "</td>";
                        html += "</tr>";
                    });
                    $("#tablaSeries tbody").html(html);
                }
            });
        });
    </script>
}

<table id="tablaSeries" class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Imagen</th>
            <th>Puntuación</th>
            <th>Año</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Views/SeriesServidor/CreatePersonaje.cshtml
@model MvcExamenPracticoAzureMariaDelMarCarrionGarcia.Models.Personaje

@{
    ViewData["Title"] = "CreatePersonaje";
}

<h1>CreatePersonaje</h1>

<hr />

<h2 style="color:forestgreen">@ViewBag.Mensaje</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePersonaje">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input name="nombre" asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input name="imagen" asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdSerie" class="control-label"></label>
                <input name="idSerie" asp-for="IdSerie" class="form-control" />
                <span asp-validation-for="IdSerie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Views/SeriesServidor/DeletePersonaje.cshtml
<h1>Eliminar personaje</h1>

<hr />

<h2 style="color:forestgreen">@ViewBag.Mensaje</h2>

<form method="post">
    <div class="form-group">
        <label>ID personaje:</label>
        <input type="number" name="idPersonaje" class="form-control" />
    </div>
    <button type="submit" class="btn btn-success">Eliminar personaje</button>
</form>

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Views/SeriesServidor/DetallesSerie.cshtml
@model MvcExamenPracticoAzureMariaDelMarCarrionGarcia.Models.Serie

@{
    ViewData["Title"] = "DetallesSerie";
}

<h1>DetallesSerie</h1>

<div>
    <h4>Serie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdSerie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdSerie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Model.Imagen" style="width:300px" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Puntuacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Puntuacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anio)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Views/SeriesServidor/Index.cshtml
<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="SeriesServidor" asp-action="Series">Series</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="SeriesServidor" asp-action="PersonajesSerie">Personajes de una serie</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="SeriesServidor" asp-action="CreatePersonaje">Crear personaje</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="SeriesServidor" asp-action="UpdateSerie">Modificar serie</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="SeriesServidor" asp-action="DeletePersonaje">Eliminar personaje</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="SeriesServidor" asp-action="MoverPersonajeSerie">Mover personaje</a>
    </li>
</ul>

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Views/SeriesServidor/MoverPersonajeSerie.cshtml
@model List<Serie>

<h1>Mover personaje</h1>

<hr />

<h2 style="color:forestgreen">@ViewBag.Mensaje</h2>

<form method="post">
    <div class="form-group">
        <label>Seleccione una serie:</label>
        <select name="idSerie">
            @foreach(Serie serie in Model)
                {
                    <option value="@serie.IdSerie">@serie.Nombre</option>
                }
        </select>
    </div>

    <div class="form-group">
        <label>Seleccione un personaje:</label>
        <select name="idPersonaje">
            @foreach (Personaje personaje in ViewBag.Personajes)
            {
                <option value="@personaje.IdPersonaje">@personaje.Nombre</option>
            }
        </select>
    </div>
    <button type="submit" class="btn btn-info">Mover personaje</button>
</form>

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Views/SeriesServidor/PersonajesSerie.cshtml
@model IEnumerable<MvcExamenPracticoAzureMariaDelMarCarrionGarcia.Models.Personaje>

@{
    ViewData["Title"] = "PersonajesSerie";
}

<h1>PersonajesSerie</h1>

<hr />

<form method="post">
    <div class="form-group">
        <label>ID serie:</label>
        <input type="number" name="idSerie" class="form-control" />
    </div>
    <button type="submit" class="btn btn-success">Mostrar personajes</button>
</form>

@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.IdPersonaje)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Imagen)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IdSerie)
                </th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model)
    {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdPersonaje)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    <img src="@item.Imagen" style="width:300px" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdSerie)
                </td>
            </tr>
    }
        </tbody>
    </table>
}

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Views/SeriesServidor/Series.cshtml
@model IEnumerable<MvcExamenPracticoAzureMariaDelMarCarrionGarcia.Models.Serie>

@{
    ViewData["Title"] = "Series";
}

<h1>Series</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdSerie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Puntuacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Anio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdSerie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                <img src="@item.Imagen" style="width:300px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Puntuacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Anio)
            </td>
            <td>
                <a asp-controller="SeriesServidor" asp-action="DetallesSerie" asp-route-idSerie="@item.IdSerie" class="btn btn-info">Detalles</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Views/SeriesServidor/UpdateSerie.cshtml
@model MvcExamenPracticoAzureMariaDelMarCarrionGarcia.Models.Serie

@{
    ViewData["Title"] = "ModificarSerie";
}

<h1>ModificarSerie</h1>

<hr />

<h2 style="color:forestgreen">@ViewBag.Mensaje</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateSerie">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdSerie" class="control-label"></label>
                <input name="idSerie" asp-for="IdSerie" class="form-control" />
                <span asp-validation-for="IdSerie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input name="nombre" asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input name="imagen" asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Puntuacion" class="control-label"></label>
                <input name="puntuacion" asp-for="Puntuacion" class="form-control" />
                <span asp-validation-for="Puntuacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input name="anio" asp-for="Anio" class="form-control" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcExamenPracticoAzureMariaDelMarCarrionGarcia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcExamenPracticoAzureMariaDelMarCarrionGarcia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcExamenPracticoAzureMariaDelMarCarrionGarcia</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SeriesClient" asp-action="Index">Series Client</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SeriesServidor" asp-action="Index">Series Servidor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcExamenPracticoAzureMariaDelMarCarrionGarcia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>